(*
 * This file was generated by the OCamlClientCodegen generator for openapi-generator, and corrected manually
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_moderation_request_input.t : The input text to classify
 *)

type t = string list [@@deriving yojson { strict = false }, show ];;

(** The input text to classify *)
let create input : t = input
