(*
 * This file wra generated by the OCamlClientCodegen generator for openapi-generator, and corrected manually
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_completion_request_stop.t : Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence. 
 *)

(* The API supports a string or array of strings, but we can expose all functionality with the latter alone *)
type t = string list [@@deriving yojson { strict = false }, show ]

(** Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.  *)
let create stops : t =
  (* TODO: Add validation that list has 1 to 4 items *)
  stops
