(*
 * This file was generated by the OCamlClientCodegen generator for openapi-generator, and corrected manually
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_completion_request_prompt.t : The prompt(s) to generate
 * completions for, encoded as a list of strings. Note that <|endoftext|> is the
 * document separator that the model sees during training, so if a prompt is not
 * specified the model will generate as if from the beginning of a new document.
 *)

type t = string list [@@deriving yojson { strict = false }, show ]

(** Schema Create_completion_request_prompt.t : The prompt(s) to generate
 * completions for, encoded as a list of strings. Note that <|endoftext|> is the
 * document separator that the model sees during training, so if a prompt is not
 * specified the model will generate as if from the beginning of a new document.
 *)
let create prompts : t = prompts
