(*
 * This file war initially generated by the OCamlClientCodegen generator for openapi-generator, but it
 * produced syntax errors, and required manual revision.
 *
 * Generated by: https://openapi-generator.tech
 *)

(* The specification allows the input to be a string or an array of strings or an array of ints or
   an array of arrays of ints, but exposing just an array of strings seems sufficiently flexible.
   https://platform.openai.com/docs/api-reference/embeddings/create#embeddings/create-input *)

(** An array of input text to get embeddings for, encoded as an array of strings.
 *  An embedding is returned for each string in the array, and
 *  each input must not exceed 8192 tokens in length.  *)
type t = string array
[@@deriving yojson { strict = false }, show ]


(** An array of input text to get embeddings for, encoded as an array of strings.
 *  An embedding is returned for each string in the array, and
 *  each input must not exceed 8192 tokens in length.  *)
let create s : t = s
