(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_moderation_request_input.t : The input text to classify
 *)

type t = {
} [@@deriving yojson { strict = false }, show ];;

(** The input text to classify *)
let create () : t = {
}

