(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Create_answer_request_stop.t : Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence. 
 *)

type t = {
} [@@deriving yojson { strict = false }, show ];;

(** Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.  *)
let create () : t = {
}

