(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them. *)
    model: string;
    input: Create_embedding_request_input.t;
    (* A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).  *)
    user: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (model : string) (input : Create_embedding_request_input.t) : t = {
    model = model;
    input = input;
    user = None;
}

